//! BSN source emitter — generates `bsn!` / `bsn_list!` Rust code from a `BsnIr`.
//!
//! See ADR-0005 §Implementation Direction item 4.
//! Coexists with `code_export::export_rust_source`; neither calls the other.

use std::fmt::Write as FmtWrite;

use crate::bsn_ir::{BsnIr, BsnIrNode, bsn_ir_from_scene_asset};
use crate::code_export::CodeGenResult;
use crate::dynamic_scene::{ExportWarning, anchor_str_to_normalized_offset};
use crate::scene_asset::SceneAssetDocument;

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/// Emit `bsn!` / `bsn_list!` Rust source from a pre-built `BsnIr`.
pub fn emit_bsn_source(ir: &BsnIr, scene_name: &str) -> CodeGenResult {
    let mut out = String::new();
    let mut warnings = Vec::new();

    emit_header(&mut out);
    emit_spawn_function(&mut out, ir, scene_name, &mut warnings);

    if !out.ends_with('\n') {
        out.push('\n');
    }

    CodeGenResult {
        source: out,
        warnings,
    }
}

/// Build `BsnIr` from a `SceneAssetDocument` and emit `bsn!` source.
pub fn emit_bsn_source_from_document(doc: &SceneAssetDocument, scene_name: &str) -> CodeGenResult {
    let ir = bsn_ir_from_scene_asset(doc);
    emit_bsn_source(&ir, scene_name)
}

// ─────────────────────────────────────────────────────────────────────────────
// Private helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Emits the file header comment block and `use` statement.
fn emit_header(out: &mut String) {
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(
        out,
        "// ⚠️  AUTO-GENERATED — edits will be lost on next export"
    )
    .unwrap();
    writeln!(
        out,
        "// Bevy 0.19 | Generated by Bevy 2D Editor | BSN output"
    )
    .unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use bevy::prelude::*;").unwrap();
    writeln!(out).unwrap();
}

/// Emits the `spawn_<scene_name>` function wrapping `bsn_list!`.
fn emit_spawn_function(
    out: &mut String,
    ir: &BsnIr,
    scene_name: &str,
    warnings: &mut Vec<ExportWarning>,
) {
    let snake = to_snake_case(scene_name);
    writeln!(out, "pub fn spawn_{}(mut commands: Commands) {{", snake).unwrap();
    writeln!(out, "    commands.spawn_scene_list(bsn_list![").unwrap();
    emit_bsn_list_body(out, ir, warnings);
    writeln!(out, "    ]).unwrap();").unwrap();
    writeln!(out, "}}").unwrap();
}

/// Emits the body of `bsn_list![ ... ]`.
/// - 0 roots → `// Empty scene`
/// - 1+ roots → `bsn!{ ... }` blocks, comma-separated at column 0
fn emit_bsn_list_body(out: &mut String, ir: &BsnIr, warnings: &mut Vec<ExportWarning>) {
    if ir.scene_root.components.is_empty() && ir.scene_root.children.is_empty() {
        writeln!(out, "        // Empty scene").unwrap();
        return;
    }

    emit_bsn_node(out, &ir.scene_root, 1, warnings);
}

/// Recursively emits a single `bsn!{ ... }` block for a `BsnIrNode`.
fn emit_bsn_node(
    out: &mut String,
    node: &BsnIrNode,
    indent: usize,
    warnings: &mut Vec<ExportWarning>,
) {
    let indent_str = "    ".repeat(indent);

    writeln!(out, "{}bsn!{{", indent_str).unwrap();
    writeln!(out, "{}#{}", indent_str, node.identifier).unwrap();

    // Emit components in alphabetical order (BTreeMap iteration is sorted)
    for (type_id, values) in &node.components {
        emit_component(out, type_id, values, indent + 1, warnings);
    }

    // Emit children as `Children [ ... ]`
    if !node.children.is_empty() {
        writeln!(out, "{}Children [", indent_str).unwrap();
        for child in &node.children {
            emit_bsn_node(out, child, indent + 2, warnings);
            writeln!(out, "{}    ,", indent_str).unwrap();
        }
        writeln!(out, "{}]", indent_str).unwrap();
    }

    writeln!(out, "{}}}", indent_str).unwrap();
}

/// Emits a single component inside a `bsn!{ ... }` block.
///
/// Returns early (no emission) for editor-only types that are silently skipped.
/// Warns and skips for truly unknown type_ids.
fn emit_component(
    out: &mut String,
    type_id: &str,
    values: &serde_json::Value,
    indent: usize,
    warnings: &mut Vec<ExportWarning>,
) {
    let indent_str = "    ".repeat(indent);

    match type_id {
        t if is_editor_only_type(t) => {
            // Silently skip: editor.Visible, editor.Locked
        }
        "editor.Name" => {
            let name = values.get("name").and_then(|v| v.as_str()).unwrap_or("");
            writeln!(out, "{}Name(\"{}\"),", indent_str, escape_string(name)).unwrap();
        }
        "editor.Transform2D" => {
            let tx = values
                .get("translation")
                .and_then(|v| v.get("x"))
                .and_then(|v| v.as_f64())
                .unwrap_or(0.0) as f32;
            let ty = values
                .get("translation")
                .and_then(|v| v.get("y"))
                .and_then(|v| v.as_f64())
                .unwrap_or(0.0) as f32;
            let rot = values
                .get("rotation")
                .and_then(|v| v.as_f64())
                .unwrap_or(0.0) as f32;
            let sx = values
                .get("scale")
                .and_then(|v| v.get("x"))
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0) as f32;
            let sy = values
                .get("scale")
                .and_then(|v| v.get("y"))
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0) as f32;
            writeln!(out, "{}Transform {{ translation: Vec2::new({}, {}), rotation: {}, scale: Vec2::new({}, {}) }},", indent_str, tx, ty, rot, sx, sy).unwrap();
        }
        "editor.Sprite2D" => {
            let asset = values.get("asset").and_then(|v| v.as_str()).unwrap_or("");
            let r = values
                .get("color")
                .and_then(|v| v.get("r"))
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0) as f32;
            let g = values
                .get("color")
                .and_then(|v| v.get("g"))
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0) as f32;
            let b = values
                .get("color")
                .and_then(|v| v.get("b"))
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0) as f32;
            let a = values
                .get("color")
                .and_then(|v| v.get("a"))
                .and_then(|v| v.as_f64())
                .unwrap_or(1.0) as f32;
            let anchor_str = values
                .get("anchor")
                .and_then(|v| v.as_str())
                .unwrap_or("Center");

            writeln!(
                out,
                "{}Sprite {{ image: \"{}\", color: Color::srgba({}, {}, {}, {}) }},",
                indent_str,
                escape_string(asset),
                r,
                g,
                b,
                a
            )
            .unwrap();

            // Emit Anchor as a sibling component if non-default
            let (ax, ay) = anchor_str_to_normalized_offset(anchor_str);
            // Only emit anchor if it's not Center (0.0, 0.0)
            if ax != 0.0 || ay != 0.0 {
                writeln!(out, "{}Anchor(Vec2::new({}, {})),", indent_str, ax, ay).unwrap();
            }
        }
        t if is_user_type(t) => {
            // game.* — emit as PascalCase struct literal
            let struct_name = pascal_case_struct_name(t);
            let fields = emit_struct_fields(values, warnings);
            writeln!(out, "{}{} {{ {} }},", indent_str, struct_name, fields).unwrap();
        }
        unknown => {
            warnings.push(ExportWarning {
                entity_stable_id: None,
                component_type_id: Some(unknown.to_string()),
                message: format!("Unknown component '{}' skipped", unknown),
            });
        }
    }
}

/// Emits field initializers for a `game.*` struct literal from `serde_json::Value`.
/// Handles: String → `"..."`, Number → numeric, Bool → true/false, Null → Default::default().
/// Warns and skips Object/Array.
fn emit_struct_fields(values: &serde_json::Value, warnings: &mut Vec<ExportWarning>) -> String {
    let mut parts = Vec::new();

    if let serde_json::Value::Object(obj) = values {
        for (k, v) in obj {
            let lit = format_bsn_literal(v);
            if lit.is_empty() {
                // Object/Array — cannot emit as bare bsn! literal; warn and skip
                warnings.push(ExportWarning {
                    entity_stable_id: None,
                    component_type_id: None,
                    message: format!(
                        "Object/Array field '{}' cannot be represented in bsn! source; skipped",
                        k
                    ),
                });
                continue;
            }
            parts.push(format!("{}: {}", k, lit));
        }
    }

    parts.join(", ")
}

/// Returns true for editor-only type_ids that are silently skipped.
/// Only `editor.Visible` and `editor.Locked` are truly editor-only.
/// `editor.Name`, `editor.Transform2D`, `editor.Sprite2D` have Bevy equivalents and are emitted.
fn is_editor_only_type(type_id: &str) -> bool {
    matches!(type_id, "editor.Visible" | "editor.Locked")
}

/// Returns true if `type_id` is a user-defined `game.*` type.
fn is_user_type(type_id: &str) -> bool {
    type_id.starts_with("game.")
}

/// Converts a `type_id` to the matching Rust struct name in PascalCase.
/// Mirrors `code_export::struct_name_for_type_id`.
fn pascal_case_struct_name(type_id: &str) -> String {
    let stripped = type_id.strip_prefix("game.").unwrap_or(type_id);
    let pascal = to_pascal_case(stripped);
    if pascal
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        format!("_{}", pascal)
    } else {
        pascal
    }
}

/// Converts a `snake_case` or `SCREAMING_SNAKE` string to PascalCase.
/// Leaves already-PascalCase strings unchanged.
fn to_pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '_' || c == ' ' {
            capitalize_next = true;
        } else if capitalize_next {
            out.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            out.push(c.to_ascii_lowercase());
        }
    }
    out
}

/// Converts a scene / struct name to snake_case.
/// - ASCII letters are lowercased
/// - Non-alphanumeric bytes become `_`
/// - Consecutive `_` are collapsed
/// - Leading/trailing `_` are trimmed
/// - Empty result → `"scene"`
fn to_snake_case(s: &str) -> String {
    let mut out = Vec::new();
    let mut prev_underscore = false;

    for byte in s.bytes() {
        if byte.is_ascii_alphanumeric() {
            out.push(byte.to_ascii_lowercase());
            prev_underscore = false;
        } else {
            if !prev_underscore && !out.is_empty() {
                out.push(b'_');
                prev_underscore = true;
            }
        }
    }

    // Trim trailing underscore
    while out.last() == Some(&b'_') {
        out.pop();
    }

    let result = String::from_utf8(out).unwrap_or_default();
    if result.is_empty() {
        "scene".to_string()
    } else {
        result
    }
}

/// Formats a `serde_json::Value` as a Rust literal for `bsn!` patch syntax.
/// - `Value::String(s)` → `"<escaped>"`
/// - `Value::Number(n)` → numeric string (integer or with decimal)
/// - `Value::Bool(b)` → `true` / `false`
/// - `Value::Null` → `Default::default()`
/// - `Value::Object` / `Value::Array` → emits nothing (caller should warn + skip)
fn format_bsn_literal(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => format!("\"{}\"", escape_string(s)),
        serde_json::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                i.to_string()
            } else if let Some(f) = n.as_f64() {
                let s = f.to_string();
                if s.contains('.') || s.contains('e') || s.contains('E') {
                    s
                } else {
                    format!("{}.0", s)
                }
            } else {
                String::new()
            }
        }
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "Default::default()".to_string(),
        serde_json::Value::Object(_) | serde_json::Value::Array(_) => {
            // Cannot emit Object/Array as a bare bsn! literal; skip field
            String::new()
        }
    }
}

/// Escapes a Rust string literal: only `\` and `"` are escaped.
/// All other characters (including newlines) pass through as-is.
fn escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c => out.push(c),
        }
    }
    out
}
