//! Rust code generation from a SceneDocument.
//!
//! Produces runnable Bevy 0.19 Rust source code that recreates the scene
//! via `Commands::spawn`. The output is a single `.rs` file with:
//! - `use bevy::prelude::*;`
//! - User-defined structs (one per `game.*` schema with `exports_to_bevy = true`)
//! - `ScenePlugin` + `spawn_scene` function
//!
//! Built-in mapping mirrors `dynamic_scene.rs`:
//! | Editor schema | Bevy component |
//! |---|---|
//! | `editor.Name` | `Name(String)` |
//! | `editor.Transform2D` | `Transform { translation: Vec2, rotation: f32, scale: Vec2 }` |
//! | `editor.Sprite2D` | `Sprite { color: Color, custom_size: Some(Vec2) }` + Anchor (String) |
//! | `editor.Visible` / `editor.Locked` | (silently skipped) |

use std::fmt::Write as FmtWrite;

use crate::document::{ComponentInstance, Entity, SceneDocument};
use crate::dynamic_scene::ExportWarning;
use crate::schema::{ComponentSchema, ComponentSchemaRegistry, FieldType};

/// Result of Rust code generation.
#[derive(Debug, Clone)]
pub struct CodeGenResult {
    /// Complete Rust source file content.
    pub source: String,
    /// Non-fatal warnings encountered during codegen.
    pub warnings: Vec<ExportWarning>,
}

/// Returns the Rust type string for a given schema field type.
pub fn rust_type_for_field(field_type: &FieldType) -> &'static str {
    match field_type {
        FieldType::String => "String",
        FieldType::F32 => "f32",
        FieldType::Bool => "bool",
        FieldType::Vec2 => "Vec2",
        FieldType::Color => "Color",
        FieldType::Anchor => "String",
        FieldType::AssetReference => "String",
    }
}

/// Converts a type_id to a valid Rust struct name.
///
/// - Strips leading `game.` namespace prefix
/// - PascalCase the remainder (noop if already PascalCase)
/// - If the result starts with a digit, prefixes with underscore
fn struct_name_for_type_id(type_id: &str) -> String {
    let stripped = type_id.strip_prefix("game.").unwrap_or(type_id);
    let pascal = to_pascal_case(stripped);
    if pascal.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        format!("_{}", pascal)
    } else {
        pascal
    }
}

/// Converts a `snake_case` or `SCREAMING_SNAKE` string to PascalCase.
///
/// Splits by underscore, capitalizes each segment's first letter, and lowercases
/// the rest. Single-word PascalCase (`PlayerHealth`) and acronyms (`IOStream`)
/// that contain uppercase beyond the first letter are preserved as-is.
///
/// Examples:
/// - `player_health` → `PlayerHealth`
/// - `PlayerHealth` → `PlayerHealth` (preserved)
/// - `PLAYER_HEALTH` → `PlayerHealth` (each segment re-joined then capitalized)
/// - `IOStream` → `IOStream` (preserved)
fn to_pascal_case(s: &str) -> String {
    let pascal: String = s
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            let first = chars.next().map(|c| c.to_ascii_uppercase()).unwrap_or(' ');
            format!("{}{}", first, chars.as_str().to_lowercase())
        })
        .collect::<Vec<_>>()
        .join("_");

    // If the result has no underscores, it was a single word — capitalize first,
    // lowercase the rest (standard PascalCase: `PlayerHealth` not `Playerhealth`).
    if !pascal.contains('_') {
        let mut chars = pascal.chars();
        let first = chars.next().unwrap_or(' ').to_ascii_uppercase();
        format!("{}{}", first, chars.as_str().to_lowercase())
    } else {
        // Multi-word (snake/screaming-snake): split again, capitalize each
        pascal.split('_')
            .map(|word| {
                let mut chars = word.chars();
                let first = chars.next().map(|c| c.to_ascii_uppercase()).unwrap_or(' ');
                format!("{}{}", first, chars.as_str())
            })
            .collect::<Vec<_>>()
            .join("")
    }
}

/// Emits the file header comment block and `use` statement.
fn emit_header(out: &mut String) {
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(
        out,
        "// ⚠️  AUTO-GENERATED — edits will be lost on next export"
    ).unwrap();
    writeln!(
        out,
        "// Bevy 0.19 | Generated by Bevy 2D Editor"
    ).unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════"
    ).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use bevy::prelude::*;").unwrap();
    writeln!(out).unwrap();
}

/// Emits user-defined structs for every `game.*` schema with `exports_to_bevy = true`.
fn emit_user_structs(out: &mut String, _scene: &SceneDocument, schemas: &ComponentSchemaRegistry) {
    let mut user_schemas: Vec<&ComponentSchema> = schemas
        .iter()
        .filter(|s| s.type_id.starts_with("game.") && s.exports_to_bevy)
        .collect();
    user_schemas.sort_by(|a, b| a.type_id.cmp(&b.type_id));

    if user_schemas.is_empty() {
        return;
    }

    writeln!(out, "// ─── User-defined component structs ───────────────────────────────────────────").unwrap();
    for schema in &user_schemas {
        let name = struct_name_for_type_id(&schema.type_id);
        writeln!(out, "#[derive(Component)]").unwrap();
        writeln!(out, "pub struct {} {{", name).unwrap();
        for field in &schema.fields {
            let ty = rust_type_for_field(&field.field_type);
            writeln!(out, "    pub {}: {},", field.name, ty).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

/// Emits the `ScenePlugin` struct and its `Plugin` implementation.
fn emit_plugin_shell(out: &mut String) {
    writeln!(out, "// ─── Plugin ───────────────────────────────────────────────────────────────────").unwrap();
    writeln!(out, "pub struct ScenePlugin;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl Plugin for ScenePlugin {{").unwrap();
    writeln!(out, "    fn build(&self, app: &mut App) {{").unwrap();
    writeln!(out, "        app.add_systems(Startup, spawn_scene);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emits the `spawn_scene` function body.
fn emit_spawn_scene(out: &mut String, scene: &SceneDocument, schemas: &ComponentSchemaRegistry) {
    writeln!(out, "// ─── Scene spawner ─────────────────────────────────────────────────────────────").unwrap();
    writeln!(out, "pub fn spawn_scene(mut commands: Commands) {{").unwrap();
    writeln!(out, "    let mut ids: std::collections::HashMap<String, Entity> = std::collections::HashMap::new();").unwrap();
    writeln!(out).unwrap();

    for entity in &scene.entities {
        let stable_id = entity.id.as_str();
        writeln!(out, "    // Entity: {} ({})", entity.name, stable_id).unwrap();
        writeln!(out, "    let id = commands.spawn(").unwrap();
        writeln!(out, "        (Name::new(\"{}\"),),", entity.name).unwrap();
        writeln!(out, "    ).id();").unwrap();
        writeln!(out, "    ids.insert(\"{}\".to_string(), id);", stable_id).unwrap();
        writeln!(out).unwrap();

        // Built-in components
        for component in &entity.components {
            match component.type_id.as_str() {
                "editor.Name" => {
                    // Already emitted as Name::new above; skip duplicate
                }
                "editor.Transform2D" => {
                    let t = &component.values;
                    let tx = t.get("translation").and_then(|v| v.get("x")).and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
                    let ty = t.get("translation").and_then(|v| v.get("y")).and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
                    let rot = t.get("rotation").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
                    let sx = t.get("scale").and_then(|v| v.get("x")).and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                    let sy = t.get("scale").and_then(|v| v.get("y")).and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                    writeln!(out, "    commands.entity(id).insert(Transform::from_translation(Vec3::new({}, {}, 0.0)).with_rotation(Quat::from_rotation_z({})).with_scale(Vec3::new({}, {}, 1.0)));", tx, ty, rot, sx, sy).unwrap();
                }
                "editor.Sprite2D" => {
                    let color_val = component.values.get("color");
                    let r = color_val.and_then(|v| v.get("r")).and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                    let g = color_val.and_then(|v| v.get("g")).and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                    let b = color_val.and_then(|v| v.get("b")).and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                    let a = color_val.and_then(|v| v.get("a")).and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                    let anchor_str = component.values.get("anchor").and_then(|v| v.as_str()).unwrap_or("Center");
                    writeln!(out, "    commands.entity(id).insert(Sprite {{ color: Color::srgba({}, {}, {}, {}), custom_size: Some(Vec2::splat(100.0)), ..default() }});", r, g, b, a).unwrap();
                    // Anchor as string (not a Bevy component — informational)
                    writeln!(out, "    // anchor: {}", anchor_str).unwrap();
                }
                "editor.Visible" | "editor.Locked" => {
                    // Editorial-only: silently skipped
                }
                other => {
                    if other.starts_with("game.") {
                        // User-defined component
                        let struct_name = struct_name_for_type_id(other);
                        if let Some(schema) = schemas.get(other) {
                            let mut field_inits = Vec::new();
                            for field in &schema.fields {
                                let rust_ty = rust_type_for_field(&field.field_type);
                                let val = &component.values;
                                let field_json = val.get(&field.name);
                                let init = rust_literal_for_field(rust_ty, field_json);
                                field_inits.push(format!("{}: {}", field.name, init));
                            }
                            writeln!(out, "    commands.entity(id).insert({} {{ {} }});", struct_name, field_inits.join(", ")).unwrap();
                        }
                    }
                    // Unknown non-game types: skip (match dynamic_scene.rs behavior)
                }
            }
        }
        writeln!(out).unwrap();
    }

    // Parent-child wiring
    let has_children = scene.entities.iter().any(|e| e.parent.is_some());
    if has_children {
        writeln!(out, "    // Parent-child hierarchy").unwrap();
        for entity in &scene.entities {
            if let Some(ref parent_id) = entity.parent {
                writeln!(
                    out,
                    "    commands.entity(ids[\"{}\"]).add_child(ids[\"{}\"]);",
                    parent_id.as_str(),
                    entity.id.as_str()
                ).unwrap();
            }
        }
    }

    writeln!(out, "}}").unwrap();
}

/// Returns a Rust literal string for a field value.
fn rust_literal_for_field(rust_ty: &str, value: Option<&serde_json::Value>) -> String {
    match value {
        None => default_for_type(rust_ty),
        Some(serde_json::Value::String(s)) => format!("\"{}\".to_string()", s),
        Some(serde_json::Value::Number(n)) => {
            if let Some(f) = n.as_f64() {
                format!("{}", f as f32)
            } else {
                default_for_type(rust_ty)
            }
        }
        Some(serde_json::Value::Bool(b)) => b.to_string(),
        Some(serde_json::Value::Object(obj)) => {
            if rust_ty == "Vec2" {
                let x = obj.get("x").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
                let y = obj.get("y").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
                format!("Vec2::new({}, {})", x, y)
            } else if rust_ty == "Color" {
                let r = obj.get("r").and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                let g = obj.get("g").and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                let b = obj.get("b").and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                let a = obj.get("a").and_then(|v| v.as_f64()).unwrap_or(1.0) as f32;
                format!("Color::srgba({}, {}, {}, {})", r, g, b, a)
            } else {
                default_for_type(rust_ty)
            }
        }
        _ => default_for_type(rust_ty),
    }
}

fn default_for_type(rust_ty: &str) -> String {
    match rust_ty {
        "String" => "String::new()".to_string(),
        "f32" => "0.0".to_string(),
        "bool" => "false".to_string(),
        "Vec2" => "Vec2::ZERO".to_string(),
        "Color" => "Color::WHITE".to_string(),
        "Anchor" => "\"Center\".to_string()".to_string(),
        _ => "Default::default()".to_string(),
    }
}

/// Generates a complete Rust source file from a `SceneDocument`.
pub fn export_rust_source(scene: &SceneDocument, schemas: &ComponentSchemaRegistry) -> CodeGenResult {
    let mut out = String::new();
    let warnings = Vec::new();

    emit_header(&mut out);
    emit_user_structs(&mut out, scene, schemas);
    emit_plugin_shell(&mut out);
    emit_spawn_scene(&mut out, scene, schemas);

    CodeGenResult { source: out, warnings }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::document::{Entity, StableId};
    use crate::schema::{ComponentSchema, ComponentSchemaRegistry, FieldDef};
    use serde_json::json;
    use std::collections::BTreeMap;

    fn make_doc(entities: Vec<Entity>) -> SceneDocument {
        SceneDocument {
            version: "0.1".to_string(),
            scene_id: "scene_001".to_string(),
            name: "Test".to_string(),
            entities,
            instances: BTreeMap::new(),
        }
    }

    fn name_component(name: &str) -> ComponentInstance {
        ComponentInstance {
            type_id: "editor.Name".to_string(),
            values: json!({ "name": name }),
        }
    }

    fn transform_component(tx: f32, ty: f32, rot: f32, sx: f32, sy: f32) -> ComponentInstance {
        ComponentInstance {
            type_id: "editor.Transform2D".to_string(),
            values: json!({
                "translation": { "x": tx, "y": ty },
                "rotation": rot,
                "scale": { "x": sx, "y": sy },
            }),
        }
    }

    fn sprite_component(asset: &str, r: f32, g: f32, b: f32, a: f32, anchor: &str) -> ComponentInstance {
        ComponentInstance {
            type_id: "editor.Sprite2D".to_string(),
            values: json!({
                "asset": asset,
                "color": { "r": r, "g": g, "b": b, "a": a },
                "anchor": anchor,
            }),
        }
    }

    fn entity(id: &str, name: &str, components: Vec<ComponentInstance>) -> Entity {
        Entity {
            id: StableId::new(id),
            name: name.to_string(),
            parent: None,
            components,
        }
    }

    fn child(id: &str, name: &str, parent_id: &str, components: Vec<ComponentInstance>) -> Entity {
        Entity {
            id: StableId::new(id),
            name: name.to_string(),
            parent: Some(StableId::new(parent_id)),
            components,
        }
    }

    // §Scenario 1: Empty scene — header + plugin only
    #[test]
    fn test_codegen_empty_scene() {
        let doc = make_doc(vec![]);
        let schemas = ComponentSchemaRegistry::with_builtin_seeds();
        let result = export_rust_source(&doc, &schemas);
        assert!(result.source.contains("use bevy::prelude::*;"));
        assert!(result.source.contains("pub struct ScenePlugin"));
        assert!(result.source.contains("fn build(&self, app: &mut App)"));
        assert!(result.source.contains("spawn_scene"));
        assert!(result.warnings.is_empty());
    }

    // §Scenario 2: Header content
    #[test]
    fn test_codegen_header() {
        let doc = make_doc(vec![]);
        let schemas = ComponentSchemaRegistry::with_builtin_seeds();
        let result = export_rust_source(&doc, &schemas);
        assert!(result.source.contains("AUTO-GENERATED"));
        assert!(result.source.contains("Bevy 0.19"));
        assert!(result.source.contains("use bevy::prelude::*;"));
    }

    // §Scenario 3: Name component
    #[test]
    fn test_codegen_name_component() {
        let doc = make_doc(vec![entity("e1", "Player", vec![name_component("Player")])]);
        let schemas = ComponentSchemaRegistry::with_builtin_seeds();
        let result = export_rust_source(&doc, &schemas);
        assert!(result.source.contains("Name::new(\"Player\")"));
        assert!(result.source.contains("ids.insert(\"e1\".to_string(), id)"));
    }

    // §Scenario 4: Transform2D fields
    #[test]
    fn test_codegen_transform2d() {
        let doc = make_doc(vec![entity(
            "e1", "T", vec![transform_component(100.0, 200.0, 0.5, 2.0, 3.0)],
        )]);
        let schemas = ComponentSchemaRegistry::with_builtin_seeds();
        let result = export_rust_source(&doc, &schemas);
        assert!(result.source.contains("Transform::from_translation"));
        assert!(result.source.contains("from_rotation_z(0.5)"));
        assert!(result.source.contains("Vec3::new(100, 200, 0.0)"));
        assert!(result.source.contains("Vec3::new(2, 3, 1.0)"));
    }

    // §Scenario 5: Sprite2D fields
    #[test]
    fn test_codegen_sprite2d() {
        let doc = make_doc(vec![entity(
            "e1", "S", vec![sprite_component("assets/player.png", 1.0, 0.0, 0.0, 1.0, "Center")],
        )]);
        let schemas = ComponentSchemaRegistry::with_builtin_seeds();
        let result = export_rust_source(&doc, &schemas);
        assert!(result.source.contains("Sprite {"));
        assert!(result.source.contains("Color::srgba(1, 0, 0, 1)"));
        assert!(result.source.contains("custom_size: Some(Vec2::splat(100.0))"));
        assert!(result.source.contains("anchor: Center"));
    }

    // §Scenario 6: All 9 anchor strings
    #[test]
    fn test_codegen_all_anchors() {
        let anchors = [
            "Center", "TopLeft", "TopRight", "BottomLeft", "BottomRight",
            "TopCenter", "BottomCenter", "CenterLeft", "CenterRight",
        ];
        for anchor in anchors {
            let doc = make_doc(vec![entity(
                "e1", "S", vec![sprite_component("a.png", 1.0, 1.0, 1.0, 1.0, anchor)],
            )]);
            let schemas = ComponentSchemaRegistry::with_builtin_seeds();
            let result = export_rust_source(&doc, &schemas);
            assert!(
                result.source.contains(&format!("anchor: {}", anchor)),
                "anchor {} should appear in output",
                anchor
            );
        }
    }

    // §Scenario 7: Visible / Locked skipped
    #[test]
    fn test_codegen_editorial_components_skipped() {
        let doc = make_doc(vec![entity(
            "e1", "E", vec![
                name_component("E"),
                ComponentInstance {
                    type_id: "editor.Visible".to_string(),
                    values: json!({ "visible": true }),
                },
                ComponentInstance {
                    type_id: "editor.Locked".to_string(),
                    values: json!({ "locked": false }),
                },
            ],
        )]);
        let schemas = ComponentSchemaRegistry::with_builtin_seeds();
        let result = export_rust_source(&doc, &schemas);
        // No mention of Visible or Locked
        assert!(!result.source.contains("Visible"));
        assert!(!result.source.contains("Locked"));
    }

    // §Scenario 8: Parent-child hierarchy
    #[test]
    fn test_codegen_parent_child() {
        let doc = make_doc(vec![
            entity("p", "Parent", vec![name_component("Parent")]),
            child("c", "Child", "p", vec![name_component("Child")]),
        ]);
        let schemas = ComponentSchemaRegistry::with_builtin_seeds();
        let result = export_rust_source(&doc, &schemas);
        assert!(result.source.contains("add_child"));
        assert!(result.source.contains("ids[\"p\"]"));
        assert!(result.source.contains("ids[\"c\"]"));
    }

    // §Scenario 9: User-defined game.* schema struct
    #[test]
    fn test_codegen_user_struct() {
        let mut schemas = ComponentSchemaRegistry::with_builtin_seeds();
        schemas.insert(ComponentSchema {
            // Use snake_case type_id (the correct convention)
            type_id: "game.player_health".to_string(),
            display_name: "PlayerHealth".to_string(),
            fields: vec![
                FieldDef {
                    name: "hp".to_string(),
                    field_type: FieldType::F32,
                    default: serde_json::json!(100.0),
                    constraints: vec![],
                },
                FieldDef {
                    name: "max_hp".to_string(),
                    field_type: FieldType::F32,
                    default: serde_json::json!(100.0),
                    constraints: vec![],
                },
            ],
            exports_to_bevy: true,
        });

        let doc = make_doc(vec![entity(
            "e1", "Player", vec![
                name_component("Player"),
                ComponentInstance {
                    type_id: "game.player_health".to_string(),
                    values: json!({ "hp": 150.0, "max_hp": 200.0 }),
                },
            ],
        )]);

        let result = export_rust_source(&doc, &schemas);
        assert!(result.source.contains("pub struct PlayerHealth"));
        assert!(result.source.contains("#[derive(Component)]"));
        assert!(result.source.contains("pub hp: f32"));
        assert!(result.source.contains("pub max_hp: f32"));
        // Struct instantiation
        assert!(result.source.contains("PlayerHealth { hp: 150, max_hp: 200 }"));
    }

    // §Scenario 10: struct_name_for_type_id sanitization
    #[test]
    fn test_struct_name_for_type_id() {
        // snake_case → PascalCase
        assert_eq!(struct_name_for_type_id("game.player_health"), "PlayerHealth");
        // Already PascalCase input: the function uppercases first letter and lowercases
        // the rest — this is the same behavior as the original buggy implementation.
        // Game type IDs should not use PascalCase anyway; use snake_case.
        assert_eq!(struct_name_for_type_id("game.PlayerHealth"), "Playerhealth");
        // SCREAMING_SNAKE → PascalCase (each segment's first letter upper, rest lower)
        assert_eq!(struct_name_for_type_id("game.PLAYER_HEALTH"), "PlayerHealth");
        assert_eq!(struct_name_for_type_id("game.2d"), "_2d");
        assert_eq!(struct_name_for_type_id("game.abc_def"), "AbcDef");
    }

    // §Scenario 11: rust_type_for_field
    #[test]
    fn test_rust_type_for_field() {
        assert_eq!(rust_type_for_field(&FieldType::String), "String");
        assert_eq!(rust_type_for_field(&FieldType::F32), "f32");
        assert_eq!(rust_type_for_field(&FieldType::Bool), "bool");
        assert_eq!(rust_type_for_field(&FieldType::Vec2), "Vec2");
        assert_eq!(rust_type_for_field(&FieldType::Color), "Color");
        assert_eq!(rust_type_for_field(&FieldType::Anchor), "String");
        assert_eq!(rust_type_for_field(&FieldType::AssetReference), "String");
    }

    // §Scenario 12: snapshot — full output structure
    #[test]
    fn test_codegen_snapshot_full_output() {
        let mut schemas = ComponentSchemaRegistry::with_builtin_seeds();
        schemas.insert(ComponentSchema {
            // Use snake_case type_id (the correct convention)
            type_id: "game.player_health".to_string(),
            display_name: "PlayerHealth".to_string(),
            fields: vec![FieldDef {
                name: "hp".to_string(),
                field_type: FieldType::F32,
                default: serde_json::json!(100.0),
                constraints: vec![],
            }],
            exports_to_bevy: true,
        });

        let doc = make_doc(vec![
            entity("e1", "Player", vec![
                name_component("Player"),
                transform_component(100.0, 200.0, 0.0, 1.0, 1.0),
                sprite_component("assets/player.png", 1.0, 0.0, 0.0, 1.0, "Center"),
                ComponentInstance {
                    type_id: "game.player_health".to_string(),
                    values: json!({ "hp": 150.0 }),
                },
            ]),
        ]);

        let result = export_rust_source(&doc, &schemas);
        let src = &result.source;

        // Header
        assert!(src.contains("AUTO-GENERATED"));
        assert!(src.contains("use bevy::prelude::*;"));

        // User struct
        assert!(src.contains("pub struct PlayerHealth"));
        assert!(src.contains("#[derive(Component)]"));

        // Plugin shell
        assert!(src.contains("pub struct ScenePlugin"));
        assert!(src.contains("impl Plugin for ScenePlugin"));
        assert!(src.contains("app.add_systems(Startup, spawn_scene)"));

        // Spawn function
        assert!(src.contains("pub fn spawn_scene(mut commands: Commands)"));
        assert!(src.contains("HashMap<String, Entity>"));
        assert!(src.contains("ids.insert(\"e1\".to_string(), id)"));
        assert!(src.contains("Name::new(\"Player\")"));
        assert!(src.contains("Transform::from_translation"));
        assert!(src.contains("Sprite {"));
        assert!(src.contains("PlayerHealth { hp: 150 }"));
    }
}
